version: '3.8'

services:
    php:
        build: ./bin/php/${PHPVERSION}
        container_name: ${PROJECT_NAME}-php
        restart: always
        ports:
            - ${HOST_PORT}:80
        depends_on:
            - mysql
        volumes:
            - ./logs/apache:/var/log/apache2
            - ./apache/web:/var/www/html
            - ./apache/vhosts:/etc/apache2/sites-enabled
            - ./apache/php.ini:/usr/local/etc/php/php.ini
        networks:
            - ${DOCKER_NETWORK}
    mysql:
        build: ./bin/mysql/${MYSQLVERSION}
        container_name: ${PROJECT_NAME}-mysql
        restart: always
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - ./database:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - ${DOCKER_NETWORK}
# networks:
    # [network_name_here]:
        # external: true
